export default [
  {
    id: '1',
    name: 'First Name',
    value: '',
    type: 'text',
    validationMessage: 'Alphabets only. Max 15 characters',
    errorMessage: '',
  },
  {
    id: '2',
    name: 'Last Name',
    value: '',
    type: 'text',
    validationMessage: 'Alphabets only. Max 15 characters',
    errorMessage: '',
  },
  {
    id: '3',
    name: 'Email',
    value: '',
    type: 'email',
    validationMessage: 'Must follow standard email format',
    errorMessage: '',
  },
  {
    id: '4',
    name: 'Password',
    value: '',
    type: 'password',
    validationMessage: 'Must be between Six(6) to Ten(10) characters',
    errorMessage: '',
  },
  {
    id: '5',
    name: 'Confirm Password',
    value: '',
    type: 'password',
    validationMessage: 'Must be between Six(6) to Ten(10) characters',
    errorMessage: '',
  },
];
